name: Build and Lint
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Setting up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Installing and building library
        run: |
          npm install
          npm run build
      - name: Testing library
        run: |
          npm test
